#!/bin/bash
# copyright ©️ 2022 - Black Bug Group
# Author: Edgar Nyandoro - Github: Major2000



PROJDIR="$(dirname "$0")"
cd "${PROJDIR}" || return









# Help function
Help()
{
   # Display Help
   echo

   echo "Looks like you're lost, This HELP Message is enough for the guide!"

   echo

   echo "Syntax: spydomains  -[options:|u, U|f, F|o, O|h, H]  [args]"

   echo

   echo "options:"

   echo "           -u, -U     Add the domain you want to brute force for subdomains."

   echo "           -f, -F     Add a custom brute-force world list of domains"

   echo "           -o, -O     Print to  external file"

   echo "           -h, -H     Print this Help."

   echo
   
   echo  "Example: spydomains -u example.com -f wordlist.txt -o domains.txt  - With word list"

   echo  "Example: spydomains -u example.com - without word list"
  
   echo
}





# capture and check agruments
if [[ -z "$1" || "$#" == 0 ]]; then
    echo
    echo "No option(s)!"
    echo "Try -h option for HELP!"
    exit