#!/bin/bash
# copyright ©️ 2022 - Black Bug Group
# Author: Edgar Nyandoro - Github: Major2000



PROJDIR="$(dirname "$0")"
cd "${PROJDIR}" || return


if [[ -z "$1" || "$#" == 0 ]]; then
    echo
    echo "No option(s)!"
    echo "Try -h option for HELP!"
    exit